"""initial_schema

Revision ID: fce803dcba0e
Revises: 
Create Date: 2026-02-17 16:45:22.572088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce803dcba0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('primary_diagnosis', sa.String(), nullable=True),
    sa.Column('surgical_history', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('vital_signs', sa.Text(), nullable=True),
    sa.Column('post_op_instructions', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.Text(), nullable=True),
    sa.Column('previous_calls_context', sa.Text(), nullable=True),
    sa.Column('next_appointment', sa.String(), nullable=True),
    sa.Column('severity_grade', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='severitygrade'), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'CONFIRMED', 'ACTIVE', 'COMPLETED', name='patientstatus'), nullable=False),
    sa.Column('agent_persona', sa.String(), nullable=True),
    sa.Column('conversation_goal', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('escalation_keywords', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('doctor_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_patient_id'), 'conversations', ['patient_id'], unique=False)
    op.create_table('call_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'BUSY_RETRY', 'SILENT_RETRY', 'ESCALATED', 'COMPLETED', name='callstate'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('triage_classification', sa.String(), nullable=True),
    sa.Column('triage_reason', sa.String(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Integer(), nullable=True),
    sa.Column('detected_flags', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('smallest_call_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_history_patient_id'), 'call_history', ['patient_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('detected_flags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call_history.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_patient_id'), 'escalations', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escalations_patient_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_call_history_patient_id'), table_name='call_history')
    op.drop_table('call_history')
    op.drop_index(op.f('ix_conversations_patient_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('patients')
    # ### end Alembic commands ###
